name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        cabal:
          - 3.6
        ghc:
          - 8.8.4
          - 8.10.7
          - 9.0.2

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

    - name: Freeze
      run: |
        cabal freeze
    - uses: actions/cache@v2.1.6
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        cabal build all --only-dependencies
    - name: Build
      run: |
        cabal build all
    - name: Test
      run: |
        cabal test all
  stack:
    name: Stack ${{ matrix.stack }} ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.3"]
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.6
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack }}-stack

    - name: Install dependencies
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
    - name: Build
      run: |
        stack build --test --pedantic --bench --no-run-tests --no-run-benchmarks
    - name: Test
      run: |
        stack test
