name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        cabal:
          - 3.6
        ghc:
          - 8.10.7
          - 9.0.2
          - 9.2.5
          - 9.4.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always

      - name: Test
        run: cabal test --enable-tests

  stack:
    name: Stack ${{ matrix.stack }} ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.7.3"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Haskell Stack
        uses: haskell/actions/setup@v2
        with:
          stack-version: ${{ matrix.stack }}

      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.stack }}-stack
          restore-keys: |
            ${{ runner.os }}-${{ matrix.stack }}-stack
            ${{ runner.os }}-${{ matrix.stack }}-

      - name: Install dependencies
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test
